import React from 'react';
import PageTitle from '../../Comps/PageTitle/PageTitle';

const Terms = () => {
    return (
        <>
        <PageTitle title="গোপনীয়তা নীতি || Saptahik Ajkal" description="Text" />
        <div className="container">
          <div className="row my-5">
            <div className="col-lg-6">
              <div style={{ borderBottom: "2px solid var(--secondary)" }}>
                <h1 className="fw-bold secondary-color">About Us</h1>
              </div>
              {/* Content In English */}
              <div className="pt-5">
                <p>
                  Prothom Alo is committed to protecting your personal information
                  when you are using any of the websites or applications from
                  Prothom Alo. This Privacy Policy relates to use of any personal
                  information that it collects from visitors/readers via
                  following, among other, services:
                </p>
                <ul>
                  <li>
                    any Prothom Alo website that links to this privacy policy;
                  </li>
                  <li>
                    social media or official Prothom Alo content on other
                    websites;
                  </li>
                  <li>mobile and web applications (“Apps”)</li>
                </ul>
                <p>
                  In all the above services, the “Privacy Policy” shall apply only
                  when the application, website or contents therein are truly &
                  genuinely generated by Prothom Alo. Provided that no
                  application, website or contents therein are generated or
                  presented at any false or fake website, page or group in the
                  name (or with false logo) of Prothom alo, won’t get this
                  protection. Prothom Alo collects or receives information about
                  its users for many purposes; for instance, to provide services
                  designed to serve the user, to monitor and improve the services
                  offerings, for marketing or targeting advertisements etc. Such
                  information may include your name, address, phone number, email
                  address, age, social network account etc. (“the Information”).
                  There may be other privacy policies that apply to certain
                  services provided by Prothom Alo. Visitors are requested to read
                  these while registering or subscribing to these services on
                  these sites. Prothom Alo respects the privacy of its
                  visitors/readers and makes use of its best effort to ensure that
                  the information collected is used for the limited purpose for
                  which it was received.
                </p>
                <br />
                <strong>Special Precaution</strong> <br />
                <p>
                  There lies, in the name of Prothom Alo/সাপ্তাহিক আজকাল এর’,
                  multiple fake websites and facebook pages and unauthorized/
                  unwanted facebook groups in online. Prothom Alo shall hold no
                  responsibility for any content generated, published or shared in
                  those fake websites, unauthorized pages & groups in social
                  media.
                </p>
                <br />
                <strong>How Prothom Alo collects the information</strong>
                <br />
                <p>
                  Prothom Alo collects the information on a user upon the user’s
                  access to the Prothom Alo website – (i) by registering to the
                  site or Apps, (ii) subscribing to the newsletter, (iii)
                  responding to a survey or participating in a competition, (iv)
                  logging-in to a site or page, etc.
                </p>
                <p>
                  <br />
                  <strong>Third Party Advertisements and links</strong> <br />
                  At the discretion of Prothom Alo, the website or application may
                  display or allow advertisements of third party services or
                  products. These third-party sites may have separate and
                  independent privacy policies. Prothom Alo accepts no
                  responsibility or liability for the content of advertising
                  material, including, without limitation, any error, omission or
                  inaccuracy therein.. Prothom Alo does not hold any
                  responsibility for information leakage due to the visitor/reader
                  accessing a separate link, application or website, whether
                  through a link in the website or contents of Prothom Alo.
                  <br />
                  <br />
                  <strong>Use of Cookies</strong>
                  <br />
                  Prothom Alo does not collect any user data based on cookies, nor
                  does it store any sort of user information that may be personal
                  to the user. If a third party associated with the Prothom Alo
                  website collects user cookies upon your visit to the Prothom Alo
                  website, Prothom Alo does not control the use of these cookies
                  therefore you should check the relevant third-party website.
                  <br />
                  <br />
                  <strong>Demographic and purchase information</strong>
                  <br />
                  We may reference other sources of demographic and other
                  information to provide you with more targeted communications and
                  promotions. We use Google Analytics, among others, to track the
                  user behavior on our website. You can opt-out of Google
                  Analytics for Display Advertising and customize Google Display
                  Network ads using the Ads Settings options provided by Google.
                  <br />
                  <br />
                  <strong>Communication by Prothom Alo</strong> <br />
                  From time to time, Prothom Alo may contact its users via e-mail,
                  phone or SMS for invitation for participation in
                  campaigns/competitions organized by Prothom Alo, feedback,
                  survey etc, based on the information it has received from the
                  users.
                  <br />
                  <br />
                  <strong>
                    Accessing the website from outside Bangladesh
                  </strong>{" "}
                  <br />
                  All personal information submitted by users outside Bangladesh
                  will be processed in accordance with these Terms of use and
                  “Privacy Policy”.
                  <br />
                  <br />
                  <strong>Governing Law</strong> <br />
                  The laws that govern “Privacy Policy” of Prothom Alo and its
                  relationship with the user are the laws of Bangladesh and any
                  dispute regarding the use, retention, disclosure, leakage or
                  dissemination of the information or data can only be raised
                  before the courts of Bangladesh which shall have exclusive
                  jurisdiction on this matter. The entire “Privacy Policy” shall
                  apply to all who enter the website, receive service or use an
                  application from Prothom Alo regardless of their nationality,
                  location, residence or place of business.
                  <br />
                  <br />
                  <strong>Opt-out </strong> <br />
                  If, at any time, the users prefer not to receive email
                  containing marketing information from us, then the user can
                  simply follow the unsubscribe options at the bottom of each
                  email.
                  <br />
                  <br />
                  <strong>Data Retention </strong> <br />
                  We shall hold your personal information as long as your account
                  exists with Prothom Alo. We will delete your information as soon
                  as reasonably possible, based on account activity and in
                  accordance with applicable law(s), whenever you request us to do
                  so. However, we may archive and/or retain some information for
                  legal purposes.
                </p>
              </div>
            </div>
            <div className="col-lg-6">
              <div style={{ borderBottom: "2px solid var(--secondary)" }}>
                <h1 className="text-muted fw-bold secondary-color">
                  সাপ্তাহিক আজকাল এর নিয়ে
                </h1>
              </div>
              {/* Content Start In Bangla */}
              <div className="pt-5">
                <p>
                  ছাপা পত্রিকা, ওয়েব পোর্টাল, দুটি মাসিক ম্যাগাজিন (কিশোর আলো ও
                  বিজ্ঞানচিন্তা), নিয়মিত ম্যাগাজিন বর্ণিল এবং ঈদসংখ্যার মতো বিশেষ
                  ম্যাগাজিন, প্রথমা প্রকাশন, বছরব্যাপী গোলটেবিল আলোচনা, ইভেন্টস
                  (শিক্ষা, সাংস্কৃতিক ও সামাজিক কার্যক্রমসমূহ), সাপ্তাহিক আজকাল এর
                  ট্রাস্ট, সাপ্তাহিক আজকাল এর বন্ধুসভা ইত্যাদি উদ্যোগ মিলে এক
                  হাজারেরও বেশি কর্মী নিয়ে সাপ্তাহিক আজকাল এর দেশের বৃহত্তম মিডিয়া
                  প্রতিষ্ঠান। সাপ্তাহিক আজকাল এর দেশের খ্যাতনামা শিল্পগোষ্ঠী
                  ট্রান্সকম গ্রুপের অঙ্গপ্রতিষ্ঠান মিডিয়াস্টার লিমিটেডের
                  মালিকানাভুক্ত। ঢাকা, চট্টগ্রাম ও বগুড়া—এই তিন জায়গা থেকে
                  প্রতিদিন সাপ্তাহিক আজকাল এর ১০টি সংস্করণ মুদ্রিত হয়। বিচিত্র
                  সামাজিক, সাংস্কৃতিক ও শিক্ষামূলক কার্যক্রমের উদ্যোক্তা হিসেবে
                  বলা হয়ে থাকে, ‘সাপ্তাহিক আজকাল এর পত্রিকার চেয়ে একটু বেশি’।
                  <br />
                  <br />
                  যুক্তরাজ্যভিত্তিক সমীক্ষাপ্রতিষ্ঠান ক্যান্টার এমআরবি পরিচালিত
                  জাতীয় গণমাধ্যম জরিপ ২০২১ অনুসারে, প্রতিদিন ৫০ লাখের বেশি মানুষ
                  সাপ্তাহিক আজকাল এর ছাপা পত্রিকা পড়ে থাকেন। এই জরিপে দেখা গেছে,
                  প্রথম আলোই বাংলাদেশে সর্বোচ্চ পঠিত পত্রিকা।
                  <br />
                  পাঠকসংখ্যা ও পেজভিউর হিসাবেও সাপ্তাহিক আজকাল এর পোর্টাল বিশ্বে
                  বাংলা ভাষার এক নম্বর ওয়েবসাইট। প্রতি মাসে এর ভিজিটর প্রায় ১ কোটি
                  ৬০ লাখ এবং মাসিক পেজভিউ প্রায় ২২ কোটি। ১ কোটি ৯৬ লাখ অনুসারী
                  নিয়ে সাপ্তাহিক আজকাল এর ফেসবুক পেজ এখন বাংলাদেশে ব্যক্তি ও
                  প্রাতিষ্ঠানিক পেজের মধ্যে সবার শীর্ষে। সাপ্তাহিক আজকাল এর
                  আত্মপ্রকাশ ১৯৯৮ সালের ৪ নভেম্বর। বস্তুনিষ্ঠ, স্বাধীন ও
                  দলনিরপেক্ষ একটি দৈনিক পত্রিকা হিসেবে এমন এক সময়ে এর যাত্রা শুরু,
                  যখন ১৯৯০ সালে সামরিক স্বৈরতন্ত্র উচ্ছেদের এক দশকও পার হয়নি এবং
                  বাংলাদেশ নতুন করে তার গণতন্ত্রের পথ রচনার চেষ্টা করছে। পত্রিকার
                  পাশাপাশি শুরু থেকেই ডিজিটাল পরিসরে সাপ্তাহিক আজকাল এর সংবাদ
                  প্রচার করতে শুরু করে। ২০০৯ সালের ১৭ মে তারিখে হয় এর ওয়েব
                  পোর্টালের আনুষ্ঠানিক উদ্বোধন। এর আগে একই বছরের ৫ এপ্রিল চালু হয়
                  সাপ্তাহিক আজকাল এর ই–পেপার।
                  <br />
                  <br />
                  <br />
                  পত্রিকা প্রকাশের সূচনা থেকেই শ্রেণি, বয়স, লিঙ্গ, সম্প্রদায় ও
                  মতবিশ্বাস-নির্বিশেষে সবার তথ্য ও মতামতের চাহিদার প্রতি সাপ্তাহিক
                  আজকাল এর সজাগ থেকেছে। এর সম্পাদকীয় নীতির কেন্দ্রে রয়েছে উদার ও
                  বহুবাচনিক গণতন্ত্র, অসাম্প্রদায়িকতা, মুক্তিযুদ্ধের চেতনার প্রতি
                  অবিচল দায়বদ্ধতা। নারী, শিশু, ধর্মীয় সম্প্রদায় বা ক্ষুদ্র
                  জাতিসত্তার আত্মমর্যাদা ও অধিকারে সাপ্তাহিক আজকাল এর বিশ্বাসী। এর
                  সাংবাদিকতার লক্ষ্য আপামর জনমানুষের সৃষ্টিশীল উদ্যোগের সহযোগিতা
                  এবং ভবিষৎমুখী মঙ্গল ও উন্নয়ন। সম্পাদক মতিউর রহমানের নেতৃত্বে
                  একদল সৃষ্টিশীল সাংবাদিক সাপ্তাহিক আজকাল এর প্রতিষ্ঠা করেন এবং
                  দ্রুত পত্রিকা, ওয়েবসাইটসহ একে দেশের শীর্ষ গণমাধ্যম ও প্রতিষ্ঠান
                  হিসেবে গড়ে তোলেন। প্রচারসংখ্যা, প্রভাব ও মর্যাদায় সাপ্তাহিক
                  আজকাল এর বাংলাদেশের গণমাধ্যমের বিভিন্ন মাইলফলক অতিক্রম করে
                  গিয়েছে।
                  <ul>
                    <li>সাপ্তাহিক আজকাল এর যেভাবে তথ্য সংগ্রহ করে</li>
                    <li>
                      নিম্নোক্ত যেকোনো ক্ষেত্রে পাঠক সাপ্তাহিক আজকাল এরকে তথ্য
                      সংগ্রহের সার্বিক সম্মতি প্রদান করেছেন এবং এই গোপনীয়তা নীতির
                      সব শর্ত মেনে নিয়েছেন বলে ধরে নেওয়া হবে:
                    </li>
                    <li>সাইট বা অ্যাপে নিবন্ধন করলে</li>
                    <li>নিউজলেটার সাবস্ক্রাইব করলে</li>
                    <li>জরিপ বা প্রতিযোগিতায় অংশগ্রহণ করলে</li>
                    <li>সাইট বা পেজে লগইন করলে</li>
                  </ul>
                  <br />
                  <br />
                  <strong>ম্যাগাজিন</strong> <br />
                  তরুণদের মাসিকপত্র কিশোর আলোর প্রকাশনা শুরু হয় ২০১৩ সালে।
                  প্রকাশের সঙ্গে সঙ্গেই হয়ে ওঠে দেশের শীর্ষ কিশোর পত্রিকা। এরপর
                  ২০১৬ সালে বিজ্ঞানচিন্তার প্রকাশনা শুরু হয়। সারা বছর ৭টি বর্ণিল
                  ম্যাগাজিন ছাপা হয়—বর্ণিল বৈশাখ, বর্ণিল ঈদ, বর্ণিল খাবারদাবার,
                  বর্ণিল ভালো থাকুন, বর্ণিল বেড়ানো, বর্ণিল বসত এবং বর্ণিল বিয়ে। এ
                  ছাড়া ছাপা হচ্ছে বেসরকারি সংস্থার কার্যক্রম নিয়ে ম্যাগাজিন
                  উন্নয়নসঙ্গী। আর প্রতিবছর পবিত্র ঈদুল ফিতরের সময় ঈদসংখ্যা
                  প্রকাশিত হয়।
                  <br />
                  <br />
                  <strong>উদ্যোগ ও আয়োজন</strong> <br />
                  সাপ্তাহিক আজকাল এর বিভিন্ন সামাজিক, সাংস্কৃতিক ও শিক্ষামূলক
                  কার্যক্রম পরিচালনা করে থাকে। এসব কার্যক্রমের একটি বড় অংশ তরুণদের
                  সৃষ্টিশীল মানস উন্মুখ করে তোলা। কার্যক্রমগুলোর মধ্যে একদিকে আছে
                  নানা প্রতিযোগিতা, অন্যদিকে তেমনি আছে সম্মাননা ও পুরস্কার।
                  <br />
                  <br />
                  <strong>তৃতীয় পক্ষের বিজ্ঞাপন ও লিংক</strong> <br />
                  সাপ্তাহিক আজকাল এর ওয়েবসাইট ও অ্যাপে তৃতীয় পক্ষের পণ্য ও সেবার
                  বিজ্ঞাপন প্রদর্শনের অনুমতি দেওয়া হতে পারে। এই তৃতীয় পক্ষের
                  ওয়েবসাইটগুলোর গোপনীয়তার নীতি পৃথক হতে পারে। তবে এটি করা বা না
                  করার অধিকার সাপ্তাহিক আজকাল এর হাতে থাকবে। বিজ্ঞাপনের
                  বিষয়বস্তুতে কোনো ভুল, অসম্পূর্ণতা, সীমাবদ্ধতা থাকলে তার
                  দায়দায়িত্ব সাপ্তাহিক আজকাল এর গ্রহণ করবে না। ভিজিটর বা পাঠক পৃথক
                  লিংক, অ্যাপ্লিকেশন (অ্যাপ) বা ওয়েবসাইটে প্রবেশ করার কারণে তার
                  তথ্য ফাঁস হলে—সাপ্তাহিক আজকাল এর ওয়েবসাইটের লিংক বা কনটেন্টও যদি
                  তার মাধ্যম হয়—তার দায়দায়িত্ব সাপ্তাহিক আজকাল এর নেবে না।
                  <br />
                  <br />
                  <strong>কুকির ব্যবহার</strong> <br />
                  সাপ্তাহিক আজকাল এর কুকিভিত্তিক ব্যবহারকারীর উপাত্ত সংগ্রহ করে না
                  কিংবা ব্যবহারকারীর ব্যক্তিগত তথ্যও সংরক্ষণ করে না। যদি সাপ্তাহিক
                  আজকাল এর ওয়েবসাইটে প্রবেশের মাধ্যমে কোনো ব্যবহারকারীর কুকি তৃতীয়
                  পক্ষ সংগ্রহ করে, তার নিয়ন্ত্রণ সাপ্তাহিক আজকাল এর হাতে থাকবে না।
                  সে জন্য পাঠকদের তৃতীয় পক্ষের ওয়েবসাইট খতিয়ে দেখা উচিত। জনগোষ্ঠী
                  ও ক্রয়সংক্রান্ত তথ্য সুনির্দিষ্ট যোগাযোগ ও প্রচারণার জন্য আমরা
                  জনগোষ্ঠীসংক্রান্ত এবং অন্যান্য তথ্য ভিন্ন উৎস থেকে সাপ্তাহিক
                  আজকাল এর সংগ্রহ করতে পারে। এসব ক্ষেত্রে ব্যবহারকারীদের আচরণ
                  অনুসন্ধানে অন্যান্য উৎসের মধ্যে আমরা গুগল অ্যানালিটিকস ব্যবহার
                  করে থাকি। তবে পাঠক গুগলের অ্যাডস সেটিং ব্যবহার করে গুগল
                  অ্যানালিটিকসের আওতার বাইরে চলে যেতে পারেন কিংবা গুগল ডিসপ্লে
                  নেটওয়ার্ক কাস্টমাইজ করে নিতে পারেন।
                  <br />
                  <br />
                  <strong>সাপ্তাহিক আজকাল এর যোগাযোগ</strong> <br />
                  সময়ে সময়ে সাপ্তাহিক আজকাল এর ব্যবহারকারীদের সঙ্গে ইমেইল, ফোন বা
                  এসএমএসের মাধ্যমে যোগাযোগ করতে পারে। মূলত, বিভিন্ন অনুষ্ঠানে
                  যোগদানের আমন্ত্রণ, তথ্য সংগ্রহ এবং জরিপের জন্য সাপ্তাহিক আজকাল
                  এর এ যোগাযোগ করবে। ব্যবহারকারীদের কাছ থেকে সংগৃহীত তথ্যের
                  ভিত্তিতেই তা করা হবে।
                </p>
              </div>
            </div>
          </div>
        </div>
      </>
    );
};

export default Terms;