import React from "react";
import PageTitle from "../../Comps/PageTitle/PageTitle";

const Policy = () => {
  return (
    <>
      <PageTitle title="গোপনীয়তা নীতি || Saptahik Ajkal" description="Text" />
      <div className="container">
        <div className="row my-5">
          <div className="col-lg-6">
            <div style={{ borderBottom: "2px solid var(--secondary)" }}>
              <h1 className="fw-bold secondary-color">Privacy Policy</h1>
            </div>
            {/* Content In English */}
            <div className="pt-5">
              <p>
                Prothom Alo is committed to protecting your personal information
                when you are using any of the websites or applications from
                Prothom Alo. This Privacy Policy relates to use of any personal
                information that it collects from visitors/readers via
                following, among other, services:
              </p>
              <ul>
                <li>
                  any Prothom Alo website that links to this privacy policy;
                </li>
                <li>
                  social media or official Prothom Alo content on other
                  websites;
                </li>
                <li>mobile and web applications (“Apps”)</li>
              </ul>
              <p>
                In all the above services, the “Privacy Policy” shall apply only
                when the application, website or contents therein are truly &
                genuinely generated by Prothom Alo. Provided that no
                application, website or contents therein are generated or
                presented at any false or fake website, page or group in the
                name (or with false logo) of Prothom alo, won’t get this
                protection. Prothom Alo collects or receives information about
                its users for many purposes; for instance, to provide services
                designed to serve the user, to monitor and improve the services
                offerings, for marketing or targeting advertisements etc. Such
                information may include your name, address, phone number, email
                address, age, social network account etc. (“the Information”).
                There may be other privacy policies that apply to certain
                services provided by Prothom Alo. Visitors are requested to read
                these while registering or subscribing to these services on
                these sites. Prothom Alo respects the privacy of its
                visitors/readers and makes use of its best effort to ensure that
                the information collected is used for the limited purpose for
                which it was received.
              </p>
              <br />
              <strong>Special Precaution</strong> <br />
              <p>
                There lies, in the name of Prothom Alo/প্রথম আলো’, multiple fake
                websites and facebook pages and unauthorized/ unwanted facebook
                groups in online. Prothom Alo shall hold no responsibility for
                any content generated, published or shared in those fake
                websites, unauthorized pages & groups in social media.
              </p>
              <br />
              <strong>How Prothom Alo collects the information</strong>
              <br />
              <p>
                Prothom Alo collects the information on a user upon the user’s
                access to the Prothom Alo website – (i) by registering to the
                site or Apps, (ii) subscribing to the newsletter, (iii)
                responding to a survey or participating in a competition, (iv)
                logging-in to a site or page, etc.
              </p>
              <p>
                <br />
                <strong>Third Party Advertisements and links</strong> <br />
                At the discretion of Prothom Alo, the website or application may
                display or allow advertisements of third party services or
                products. These third-party sites may have separate and
                independent privacy policies. Prothom Alo accepts no
                responsibility or liability for the content of advertising
                material, including, without limitation, any error, omission or
                inaccuracy therein.. Prothom Alo does not hold any
                responsibility for information leakage due to the visitor/reader
                accessing a separate link, application or website, whether
                through a link in the website or contents of Prothom Alo.
                <br />
                <br />
                <strong>Use of Cookies</strong>
                <br />
                Prothom Alo does not collect any user data based on cookies, nor
                does it store any sort of user information that may be personal
                to the user. If a third party associated with the Prothom Alo
                website collects user cookies upon your visit to the Prothom Alo
                website, Prothom Alo does not control the use of these cookies
                therefore you should check the relevant third-party website.
                <br />
                <br />
                <strong>Demographic and purchase information</strong>
                <br />
                We may reference other sources of demographic and other
                information to provide you with more targeted communications and
                promotions. We use Google Analytics, among others, to track the
                user behavior on our website. You can opt-out of Google
                Analytics for Display Advertising and customize Google Display
                Network ads using the Ads Settings options provided by Google.
                <br />
                <br />
                <strong>Communication by Prothom Alo</strong> <br />
                From time to time, Prothom Alo may contact its users via e-mail,
                phone or SMS for invitation for participation in
                campaigns/competitions organized by Prothom Alo, feedback,
                survey etc, based on the information it has received from the
                users.
                <br />
                <br />
                <strong>
                  Accessing the website from outside Bangladesh
                </strong>{" "}
                <br />
                All personal information submitted by users outside Bangladesh
                will be processed in accordance with these Terms of use and
                “Privacy Policy”.
                <br />
                <br />
                <strong>Governing Law</strong> <br />
                The laws that govern “Privacy Policy” of Prothom Alo and its
                relationship with the user are the laws of Bangladesh and any
                dispute regarding the use, retention, disclosure, leakage or
                dissemination of the information or data can only be raised
                before the courts of Bangladesh which shall have exclusive
                jurisdiction on this matter. The entire “Privacy Policy” shall
                apply to all who enter the website, receive service or use an
                application from Prothom Alo regardless of their nationality,
                location, residence or place of business.
                <br />
                <br />
                <strong>Opt-out </strong> <br />
                If, at any time, the users prefer not to receive email
                containing marketing information from us, then the user can
                simply follow the unsubscribe options at the bottom of each
                email.
                <br />
                <br />
                <strong>Data Retention </strong> <br />
                We shall hold your personal information as long as your account
                exists with Prothom Alo. We will delete your information as soon
                as reasonably possible, based on account activity and in
                accordance with applicable law(s), whenever you request us to do
                so. However, we may archive and/or retain some information for
                legal purposes.
              </p>
            </div>
          </div>
          <div className="col-lg-6">
            <div style={{ borderBottom: "2px solid var(--secondary)" }}>
              <h1 className="text-muted fw-bold secondary-color">গোপনীয়তা নীতি</h1>
            </div>
            {/* Content Start In Bangla */}
            <div className="pt-5">
              <p>
                প্রথম আলোর ওয়েবসাইট বা অ্যাপ্লিকেশন (অ্যাপ) ব্যবহার করার সময়
                পাঠক, ভিজিটর অথবা ব্যবহারকারীর তথ্য সুরক্ষিত রাখতে আমরা
                অঙ্গীকারবদ্ধ। নিম্নোক্ত মাধ্যম থেকে সেবা গ্রহণের সময় তাঁদের যেসব
                ব্যক্তিগত তথ্য সংগৃহীত হয়, এই গোপনীয়তার নীতি সেসবের ওপর প্রযোজ্য
                হবে:
                <br />
                <br />
                <strong>
                  গোপনীয়তা নীতিসংবলিত প্রথম আলোর যেকোনো ওয়েবসাইট
                </strong>{" "}
                <br />
                সামাজিক যোগাযোগমাধ্যম বা অন্য যেকোনো ওয়েবসাইটে প্রথম আলোর
                কনটেন্ট মোবাইল ও ওয়েব অ্যাপ্লিকেশন (অ্যাপ)। প্রথম আলোর তৈরি
                অ্যাপ্লিকেশন (অ্যাপ), ওয়েবসাইট বা কনটেন্টের ক্ষেত্রেই শুধু এই
                গোপনীয়তা নীতি প্রযোজ্য হবে। কোনো নকল ওয়েবসাইট, পেজ বা গ্রুপে
                প্রচারিত বা প্রথম আলোর লোগো-সংবলিত ভুয়া কনটেন্টের ক্ষেত্রে এই
                গোপনীয়তা নীতি প্রযোজ্য হবে না। প্রথম আলো নানা উদ্দেশ্যে পাঠকদের
                তথ্য সংগ্রহ করে থাকে। উদাহরণ হিসেবে বলা যায়, পাঠকদের সেবা দেওয়া
                বা সেবার মান উন্নত করা এবং বিপণন ও প্রচারণার উদ্দেশ্যে এসব তথ্য
                সংগৃহীত হয়। এসব তথ্যের মধ্যে আছে গ্রাহকের নাম, ঠিকানা, ফোন
                নম্বর, ইমেইল ঠিকানা, বয়স, সামাজিক মাধ্যমের হিসাব ইত্যাদি
                (ইনফরমেশন বা তথ্য)। প্রথম আলোর অন্যান্য সেবার ক্ষেত্রে আলাদা
                গোপনীয়তার নীতি প্রযোজ্য হতে পারে। সে জন্য পাঠকদের প্রতি অনুরোধ,
                ওই সব সেবার জন্য নিবন্ধন করার সময় তাঁরা যেন সে-সংক্রান্ত
                নীতিমালা পড়ে নেন। প্রথম আলো পাঠকের ব্যক্তিগত গোপনীয়তার প্রতি
                শ্রদ্ধাশীল। আর তথ্য যে উদ্দেশ্যে সংগৃহীত হয়, তা যেন সেই
                উদ্দেশ্যই ব্যবহৃত হয়, তা নিশ্চিত করার সর্বোচ্চ চেষ্টা প্রথম আলো
                করে। বিশেষ সতর্কতা প্রথম আলো নামে দেশে একাধিক নকল ওয়েবসাইট আছে,
                যেগুলোর মধ্যে বিভিন্ন ভুয়া ফেসবুক পেজ এবং গ্রুপ অন্তর্ভুক্ত। ওই
                সব ভুয়া ওয়েবসাইট, পেজ বা গ্রুপে প্রচারিত কনটেন্টের দায় প্রথম
                আলোর নয়।
                <ul>
                  <li>প্রথম আলো যেভাবে তথ্য সংগ্রহ করে</li>
                  <li>
                    নিম্নোক্ত যেকোনো ক্ষেত্রে পাঠক প্রথম আলোকে তথ্য সংগ্রহের
                    সার্বিক সম্মতি প্রদান করেছেন এবং এই গোপনীয়তা নীতির সব শর্ত
                    মেনে নিয়েছেন বলে ধরে নেওয়া হবে:
                  </li>
                  <li>সাইট বা অ্যাপে নিবন্ধন করলে</li>
                  <li>নিউজলেটার সাবস্ক্রাইব করলে</li>
                  <li>জরিপ বা প্রতিযোগিতায় অংশগ্রহণ করলে</li>
                  <li>সাইট বা পেজে লগইন করলে</li>
                </ul>
                <br />
                <br />
                <strong>সংগৃহীত তথ্য প্রকাশ</strong> <br />
                ওয়েবসাইট পরিচালনা, ব্যবসা পরিচালনা ও গ্রাহকদের সেবা দেওয়ার
                প্রয়োজন ছাড়া পাঠকের ব্যক্তিগত তথ্যাবলি প্রথম আলো কারও কাছে
                বিক্রি অথবা আদান-প্রদান করে না। তবে পাঠকদের পছন্দ-অপছন্দ বুঝতে
                বা তাঁদের আরও ভালোভাবে সম্পৃক্ত করতে কিংবা গ্রাহকসংখ্যা বাড়াতে
                অভ্যন্তরীণভাবে পাঠকদের তথ্য পরস্পর আদান-প্রদান করা হতে পারে।
                উল্লিখিত কারণের বাইরে অন্য কোনোভাবে পাঠকের তথ্য ব্যবহার করার
                প্রয়োজন হলে তার জন্য প্রথম আলোর ওয়েবসাইট অথবা অ্যাপ থেকে অনুমতি
                নেওয়া হবে। তবে বাংলাদেশের কোনো আইনি বাধ্যবাধকতা থাকলে তা মানার
                জন্য প্রথম আলো পাঠকের কাছ থেকে সংগৃহীত ব্যক্তিগত তথ্য প্রকাশ বা
                সরবরাহ করতে পারে। এই গোপনীয়তার নীতিমালার বাইরে প্রথম আলো তার
                সেবাদাতা বিভিন্ন প্রতিষ্ঠান, অধিভুক্ত কোম্পানি, পরামর্শক বা
                অংশীদারদের কাছে কিংবা যারা প্রথম আলোর পক্ষ থেকে ব্যবসাসংক্রান্ত
                কাজ করে থাকে, তাদের কাছে পাঠকের তথ্য সরবরাহ করতে পারে; আবার আইনি
                প্রক্রিয়া বা অন্য কোনো ফোরামে নিজ স্বার্থ সংরক্ষণে এসব তথ্য
                আদান-প্রদান করা হতে পারে। অবৈধ কর্মকাণ্ড বন্ধ করতে বা তেমন কোনো
                কাজের তদন্তে এসব তথ্য ব্যবহৃত হতে পারে। আমাদের বা কোনো ব্যক্তির
                প্রতি হুমকি এলে সে রকম পরিস্থিতিতেও এসব তথ্য ব্যবহৃত হতে পারে।
                প্রথম আলোর নীতি বা ব্যবহারের শর্তাবলি লঙ্ঘনের ক্ষেত্রেও তা
                ব্যবহার করা হতে পারে। আমাদের সেবার শর্তাবলি মান্য করানোর
                লক্ষ্যেও এসব তথ্য ব্যবহার করা হতে পারে। এ ছাড়া গ্রাহকদের বিভিন্ন
                সেবা ও পণ্যের প্রস্তাব দেওয়ার লক্ষ্যেও এটি ব্যবহার করা হতে পারে।
                উল্লিখিত বা অন্য কোনো ক্ষেত্রে গ্রাহকের ব্যক্তিগত তথ্য প্রকাশ বা
                বণ্টন করা হলে প্রথম আলোর সর্বোচ্চ চেষ্টা থাকবে, যাতে এসব তথ্য
                কেবল ঘোষিত লক্ষ্যেই ব্যবহার করা হয়।
                <br />
                <br />
                <strong>তথ্য সংরক্ষণ</strong> <br />
                পাঠক বা ভিজিটর প্রথম আলোতে অ্যাকাউন্ট খুললে তাঁদের তথ্য সংরক্ষণ
                করা হবে। এ ছাড়া নিজস্ব তথ্য সংরক্ষণ নীতির আলোকে প্রথম আলো আরও
                কিছুদিন তথ্য সংরক্ষণ করতে পারে। অ্যাকাউন্টের মেয়াদ শেষ হলে
                পাঠকের ব্যক্তিগত তথ্যাবলি মুছে ফেলা হবে। কোনো কারণে এসব তথ্য
                মুছে ফেলতে সাধারণ সময়ের চেয়ে বেশি সময় লাগতে পারে। সে ক্ষেত্রে
                প্রথম আলোর দায় থাকবে না।
                <br />
                <br />
                <strong>তৃতীয় পক্ষের বিজ্ঞাপন ও লিংক</strong> <br />
                প্রথম আলোর ওয়েবসাইট ও অ্যাপে তৃতীয় পক্ষের পণ্য ও সেবার বিজ্ঞাপন
                প্রদর্শনের অনুমতি দেওয়া হতে পারে। এই তৃতীয় পক্ষের ওয়েবসাইটগুলোর
                গোপনীয়তার নীতি পৃথক হতে পারে। তবে এটি করা বা না করার অধিকার
                প্রথম আলোর হাতে থাকবে। বিজ্ঞাপনের বিষয়বস্তুতে কোনো ভুল,
                অসম্পূর্ণতা, সীমাবদ্ধতা থাকলে তার দায়দায়িত্ব প্রথম আলো গ্রহণ
                করবে না। ভিজিটর বা পাঠক পৃথক লিংক, অ্যাপ্লিকেশন (অ্যাপ) বা
                ওয়েবসাইটে প্রবেশ করার কারণে তার তথ্য ফাঁস হলে—প্রথম আলোর
                ওয়েবসাইটের লিংক বা কনটেন্টও যদি তার মাধ্যম হয়—তার দায়দায়িত্ব
                প্রথম আলো নেবে না।
                <br />
                <br />
                <strong>কুকির ব্যবহার</strong> <br />
                প্রথম আলো কুকিভিত্তিক ব্যবহারকারীর উপাত্ত সংগ্রহ করে না কিংবা
                ব্যবহারকারীর ব্যক্তিগত তথ্যও সংরক্ষণ করে না। যদি প্রথম আলোর
                ওয়েবসাইটে প্রবেশের মাধ্যমে কোনো ব্যবহারকারীর কুকি তৃতীয় পক্ষ
                সংগ্রহ করে, তার নিয়ন্ত্রণ প্রথম আলোর হাতে থাকবে না। সে জন্য
                পাঠকদের তৃতীয় পক্ষের ওয়েবসাইট খতিয়ে দেখা উচিত। জনগোষ্ঠী ও
                ক্রয়সংক্রান্ত তথ্য সুনির্দিষ্ট যোগাযোগ ও প্রচারণার জন্য আমরা
                জনগোষ্ঠীসংক্রান্ত এবং অন্যান্য তথ্য ভিন্ন উৎস থেকে প্রথম আলো
                সংগ্রহ করতে পারে। এসব ক্ষেত্রে ব্যবহারকারীদের আচরণ অনুসন্ধানে
                অন্যান্য উৎসের মধ্যে আমরা গুগল অ্যানালিটিকস ব্যবহার করে থাকি।
                তবে পাঠক গুগলের অ্যাডস সেটিং ব্যবহার করে গুগল অ্যানালিটিকসের
                আওতার বাইরে চলে যেতে পারেন কিংবা গুগল ডিসপ্লে নেটওয়ার্ক
                কাস্টমাইজ করে নিতে পারেন।
                <br />
                <br />
                <strong>প্রথম আলোর যোগাযোগ</strong> <br />
                সময়ে সময়ে প্রথম আলো ব্যবহারকারীদের সঙ্গে ইমেইল, ফোন বা এসএমএসের
                মাধ্যমে যোগাযোগ করতে পারে। মূলত, বিভিন্ন অনুষ্ঠানে যোগদানের
                আমন্ত্রণ, তথ্য সংগ্রহ এবং জরিপের জন্য প্রথম আলো এ যোগাযোগ করবে।
                ব্যবহারকারীদের কাছ থেকে সংগৃহীত তথ্যের ভিত্তিতেই তা করা হবে।
              </p>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default Policy;
